<a href="https://colab.research.google.com/github/mahnoorabbasi/empatheticResponseTypeSelection/blob/main/NRC_VAD_Calculations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:

#data_dir = '/content/drive/MyDrive/Colab Notebooks/Dataset/angry texts.csv'
data_dir = '/content/drive/MyDrive/Colab Notebooks/Dataset/Blame/_comma_ removed/angry texts - clean - experimental.csv'

df = pd.read_csv(data_dir)

In [ ]:
df.head()

content  Category
0  i just moved to this neighborhood and some dum...     Blame
1  I was very angry when a co worker lied about a...     Blame
2  I have a friend that has a child that is unrul...  No-Blame
3  Im always appalled when I see bullying in acti...  No-Blame
4  I find it odd -- and annoying -- when people d...  No-Blame

In [ ]:
df.content

0      i just moved to this neighborhood and some dum...
1      I was very angry when a co worker lied about a...
2      I have a friend that has a child that is unrul...
3      Im always appalled when I see bullying in acti...
4      I find it odd -- and annoying -- when people d...
                             ...                        
646    I was angry with your father for not meeting m...
647    My anger exploded because I was wanting doctor...
648                      The doctor was very rude to me.
649                        My car broke down on the way.
650                  My boss scolded me for coming late!
Name: content, Length: 651, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from scipy.sparse.csr import csr_matrix

# tfidf = TfidfVectorizer(sublinear_tf=True, min_df=5, norm='l2', encoding='latin-1', ngram_range=(1, 2), stop_words='english')

# features = tfidf.fit_transform(df.content).toarray()
vectorizer = TfidfVectorizer(analyzer='word', ngram_range=(1,1),
                     min_df = 0, stop_words='english')
tfidf_matrix =  vectorizer.fit_transform(df.content).toarray()
vocab = vectorizer.get_feature_names()
# print(vocab.sort)


In [ ]:
# print(len(vocab))
# print(vocab.index('anger'))
# vocab[1322]

1531
60


'swarm'

In [ ]:
documents_tfidf_lol = [{word:tfidf_value for word, tfidf_value in zip(vocab, sent)} 
                       for sent in tfidf_matrix]

documents_tfidf = pd.DataFrame(documents_tfidf_lol)
documents_tfidf.fillna(0, inplace=True)

documents_tfidf

10  100  1000   11   12  ...  young  younger  youplease  youtube  zero
0    0.0  0.0   0.0  0.0  0.0  ...    0.0      0.0        0.0      0.0   0.0
1    0.0  0.0   0.0  0.0  0.0  ...    0.0      0.0        0.0      0.0   0.0
2    0.0  0.0   0.0  0.0  0.0  ...    0.0      0.0        0.0      0.0   0.0
3    0.0  0.0   0.0  0.0  0.0  ...    0.0      0.0        0.0      0.0   0.0
4    0.0  0.0   0.0  0.0  0.0  ...    0.0      0.0        0.0      0.0   0.0
..   ...  ...   ...  ...  ...  ...    ...      ...        ...      ...   ...
646  0.0  0.0   0.0  0.0  0.0  ...    0.0      0.0        0.0      0.0   0.0
647  0.0  0.0   0.0  0.0  0.0  ...    0.0      0.0        0.0      0.0   0.0
648  0.0  0.0   0.0  0.0  0.0  ...    0.0      0.0        0.0      0.0   0.0
649  0.0  0.0   0.0  0.0  0.0  ...    0.0      0.0        0.0      0.0   0.0
650  0.0  0.0   0.0  0.0  0.0  ...    0.0      0.0        0.0      0.0   0.0

[651 rows x 1707 columns]

In [ ]:
print(tfidf_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
a_score_dir = '/content/drive/MyDrive/Colab Notebooks/Dataset/a-scores.csv'
a_scores = pd.read_csv(a_score_dir, index_col ="word")

In [ ]:
a_scores.head()

arousal
word              
abduction    0.990
exorcism     0.980
homicide     0.973
terrorism    0.971
aggresive    0.971

In [ ]:
# a_scores.word

In [ ]:
# documents_tfidf.year

In [ ]:
# a_scores.

In [ ]:
# a_score = list(readit)
# word='year'
# a_vocab=a_scores.word
# # print(len(a_scores))
# print(a_scores.get('year'))
# # a_scores.word["year"]
# # if "year" in a_scores.word:
# #     print("Yes, 'S Eductation' found in List : ")

In [ ]:
# word='newyear'
# try:
#     first = a_scores.loc[word]
#     score=first[0]
# except KeyError:
#     score = 0
# print(score)

# # a_scores.loc["yearss"]
# # print(first)
# # print(first[0])

0.784


In [ ]:
arousal_temp = documents_tfidf.copy()
for word in vocab:
  try:
    a_score_obj=a_scores.loc[word]
    a_score=a_score_obj[0]
  except KeyError:
    a_score = 0
  tfidfColScore=documents_tfidf[word]
  totalScore=a_score*tfidfColScore
  arousal_temp[word]=totalScore
  # finalDFrame=[word ,a_score ]
  print(word +" " +str(a_score))



In [ ]:
# temp.loc[0]
# temp['EmotionalValue']
# # temp['year']

0      0.986111
1      0.743010
2      0.795156
3      0.742909
4      0.516572
         ...   
490    0.720687
491    1.024575
492    0.585989
493    0.807263
494    0.736846
Name: EmotionalValue, Length: 495, dtype: float64

In [ ]:
arousal_temp["EmotionalValue"] = arousal_temp.sum(axis=1)
print(arousal_temp.sum(axis=1).idxmax())
arousal_temp.loc[0]
arousal_temp['EmotionalValue']
# temp['year']

168


0      2.025731
1      4.769570
2      3.760579
3      3.552002
4      2.648134
         ...   
646    2.360913
647    2.795025
648    2.828036
649    2.390361
650    1.912220
Name: EmotionalValue, Length: 651, dtype: float64

In [ ]:
base_filename = 'Values.txt'
# with open("/content/drive/MyDrive/Colab Notebooks/Dataset/a_score_tfidf-new.csv",'w') as outfile:
with open("/content/drive/MyDrive/Colab Notebooks/Dataset/Blame/_comma_ removed/a_score_tfidf-new.csv",'w') as outfile:
  arousal_temp.to_string(outfile)

In [ ]:
d_score_dir = '/content/drive/MyDrive/Colab Notebooks/Dataset/d-scores.csv'
d_scores = pd.read_csv(d_score_dir, index_col ="word")
d_scores.head()
dominance_temp = documents_tfidf.copy()
for word in vocab:
  try:
    d_score_obj=d_scores.loc[word]
    d_score=d_score_obj[0]
  except KeyError:
    d_score = 0
  tfidfColScore=documents_tfidf[word]
  totalScore=d_score*tfidfColScore
  dominance_temp[word]=totalScore
  # finalDFrame=[word ,a_score ]
  print(word +" " +str(d_score))

dominance_temp["EmotionalValue"] = dominance_temp.sum(axis=1)
print(dominance_temp.sum(axis=1).idxmax())
dominance_temp.loc[0]
dominance_temp['EmotionalValue']
with open("/content/drive/MyDrive/Colab Notebooks/Dataset/Blame/_comma_ removed/d_score_tfidf.csv",'w') as outfile:
    dominance_temp.to_string(outfile)

10 0
100 0
1000 0
11 0
12 0
12am 0
14 0
15 0
1600 0
17 0
1st 0
20 0
215 0
22 0
24 0
250 0
255 0
30 0
30c 0
30pm 0
3am 0
40 0
45 0
4am 0
4th 0
600 0
70 0
85 0
8th 0
able 0.81
absolutely 0
absurd 0.284
abuse 0.469
ac 0
accept 0.565
accident 0.336
accidents 0
accused 0.42
acknowledge 0.6609999999999999
acting 0.5
action 0.802
actions 0
acts 0
actually 0
admit 0.667
adults 0
affair 0.657
afford 0.575
afraid 0.245
age 0.498
agent 0.755
ages 0
aggravates 0.35700000000000004
aggravating 0.64
aggressive 0.648
ago 0.40399999999999997
agree 0.545
ahead 0.6729999999999999
airline 0.688
airplane 0.708
aisle 0.28300000000000003
alarms 0
allowed 0.655
altenative 0
anger 0.657
angered 0.547
angrier 0
angry 0.604
animal 0.513
anniversary 0.723
annoy 0.28600000000000003
annoyed 0.345
annoying 0.348
annoys 0.435
anoying 0
answer 0.6609999999999999
anxious 0.434
apartment 0.58
apologize 0.389
apologizing 0
appalled 0.562
apparently 0.426
appear 0.5670000000000001
applied 0
appointment 0.547
areas 0
arent

In [ ]:
v_score_dir = '/content/drive/MyDrive/Colab Notebooks/Dataset/v-scores.csv'
v_scores = pd.read_csv(v_score_dir, index_col ="word")
v_scores.head()
valence_temp = documents_tfidf.copy()
for word in vocab:
  try:
    v_score_obj=v_scores.loc[word]
    v_score=v_score_obj[0]
  except KeyError:
    v_score = 0
  tfidfColScore=documents_tfidf[word]
  totalScore=v_score*tfidfColScore
  valence_temp[word]=totalScore
  # finalDFrame=[word ,a_score ]
  print(word +" " +str(v_score))

valence_temp["EmotionalValue"] = valence_temp.sum(axis=1)
print(valence_temp.sum(axis=1).idxmax())
valence_temp.loc[0]
valence_temp['EmotionalValue']
with open("/content/drive/MyDrive/Colab Notebooks/Dataset/Blame/_comma_ removed/v_score_tfidf.csv",'w') as outfile:
    valence_temp.to_string(outfile)

10 0
100 0
1000 0
11 0
12 0
12am 0
14 0
15 0
1600 0
17 0
1st 0
20 0
215 0
22 0
24 0
250 0
255 0
30 0
30c 0
30pm 0
3am 0
40 0
45 0
4am 0
4th 0
600 0
70 0
85 0
8th 0
able 0.7859999999999999
absolutely 0
absurd 0.188
abuse 0.071
ac 0
accept 0.847
accident 0.125
accidents 0
accused 0.13
acknowledge 0.7859999999999999
acting 0.698
action 0.76
actions 0
acts 0
actually 0
admit 0.5379999999999999
adults 0
affair 0.52
afford 0.5710000000000001
afraid 0.01
age 0.561
agent 0.48
ages 0
aggravates 0.10800000000000001
aggravating 0.257
aggressive 0.125
ago 0.317
agree 0.9059999999999999
ahead 0.708
airline 0.65
airplane 0.7190000000000001
aisle 0.43799999999999994
alarms 0
allowed 0.73
altenative 0
anger 0.16699999999999998
angered 0.01
angrier 0
angry 0.122
animal 0.521
anniversary 0.88
annoy 0.094
annoyed 0.10400000000000001
annoying 0.08199999999999999
annoys 0.146
anoying 0
answer 0.537
anxious 0.281
apartment 0.7190000000000001
apologize 0.551
apologizing 0
appalled 0.19399999999999998
apparen